# Generated by Django 5.1.6 on 2025-03-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('advice_id', models.IntegerField(blank=True, null=True)),
                ('advice_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
